Bilirkisilik_Uygulamasi/Controllers/BilirkisiDosyaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bilirkisilik_Uygulamasi.Models.Entity;
using PagedList;
using PagedList.Mvc;


namespace Bilirkisilik_Uygulamasi.Controllers
{
    public class BilirkisiDosyaController : Controller
    {
        
        DBBILIRKISIEntities1 db = new DBBILIRKISIEntities1();

        // GET: BilirkisiDosya
        [Authorize]
        public ActionResult Index(string t)
        {
            List<TBL_BILIRKISILIK> listemp = db.TBL_BILIRKISILIK.Where(x=>x.DOSYADURUMU==true).ToList();
            return View(db.TBL_BILIRKISILIK.Where(x => x.DOSYANO.StartsWith(t) || t == null && x.DOSYADURUMU==true).OrderBy(x => x.GELISTARIHI).ToList());


        }

        [HttpGet]
        public ActionResult DosyaEkle()
        {
            
            //Birimler tablosundan Birim adını çekme yöntemi

            List<SelectListItem> deger1 = (from i in db.TBL_BIRIMLER.ToList()
                select new SelectListItem
                {
                    Text = i.BIRIMAD,
                    Value = i.ID.ToString()
                }).ToList();
            ViewBag.dgr1 = deger1;

            //Rapor Türü tablosundan rapor türlerini çekme yöntemi

            List<SelectListItem> deger2 = (from i in db.TBL_RAPORTURU.ToList()
                select new SelectListItem
                {
                    Text = i.RAPORTURU,
                    Value = i.ID.ToString()
                }).ToList();
            ViewBag.dgr2 = deger2;
            return View();
        }

        [HttpPost]
        public ActionResult DosyaEkle(TBL_BILIRKISILIK b)
        {
            var birim = db.TBL_BIRIMLER.Where(k => k.ID == b.TBL_BIRIMLER.ID).FirstOrDefault();
            var raptur = db.TBL_RAPORTURU.Where(y => y.ID == b.TBL_RAPORTURU.ID).FirstOrDefault();
            b.TBL_BIRIMLER= birim;
            b.TBL_RAPORTURU= raptur;

            db.TBL_BILIRKISILIK.Add(b);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DosyaDetayGetir(int id)
        {

            var deger = db.TBL_BILIRKISILIK.Find(id);

            //Birimler tablosundan Birim adını çekme yöntemi

            List<SelectListItem> deger1 = (from i in db.TBL_BIRIMLER.ToList()
                select new SelectListItem
                {
                    Text = i.BIRIMAD,
                    Value = i.ID.ToString()
                }).ToList();
            ViewBag.dgr1 = deger1;

            //Rapor Türü tablosundan rapor türlerini çekme yöntemi

            List<SelectListItem> deger2 = (from i in db.TBL_RAPORTURU.ToList()
                select new SelectListItem
                {
                    Text = i.RAPORTURU,
                    Value = i.ID.ToString()
                }).ToList();
            ViewBag.dgr2 = deger2;

            //Bilirkişi  tablosundan bilirkişileri çekme yöntemi

            List<SelectListItem> deger3 = (from i in db.TBL_BILIRKISILER.ToList()
                select new SelectListItem
                {
                    Text = i.ADSOYAD,
                    Value = i.ID.ToString()
                }).ToList();
            ViewBag.dgr3 = deger3;

            return View("DosyaDetayGetir", deger);
        }

        public ActionResult DosyaGuncelle(TBL_BILIRKISILIK b)
        {
            var degerler = db.TBL_BILIRKISILIK.Find(b.ID);


            degerler.DOSYANO = b.DOSYANO;
            degerler.GELISTARIHI = b.GELISTARIHI;
            degerler.TESLIMTARIHI = b.TESLIMTARIHI;
            degerler.UCRET = b.UCRET;

            var birimler = db.TBL_BIRIMLER.Where(k => k.ID == b.TBL_BIRIMLER.ID).FirstOrDefault();
            var raportur = db.TBL_RAPORTURU.Where(k => k.ID == b.TBL_RAPORTURU.ID).FirstOrDefault();
            var bilirkisi= db.TBL_BILIRKISILER.Where(k => k.ID == b.TBL_BILIRKISILER.ID).FirstOrDefault();

            degerler.BIRIM_ID= birimler.ID;
            degerler.RAPORTURU_ID= raportur.ID;
            degerler.BILIRKISI_ID= bilirkisi.ID;
            degerler.NOTLAR = b.NOTLAR;


            if (degerler.UCRET>0)
            {
                degerler.DOSYADURUMU = false;
                degerler.DURUM = true; 
            }
            else
            {
                degerler.DOSYADURUMU = true;
                degerler.DURUM = false;

            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        

       
    }
}

Bilirkisilik_Uygulamasi/Views/BilirkisiDosya/DosyaArama.cshtml
@model System.Collections.Generic.List<Bilirkisilik_Uygulamasi.Models.Entity.TBL_BILIRKISILIK>

Bilirkisilik_Uygulamasi/Views/BilirkisiDosya/DosyaDetayGetir.cshtml
@model Bilirkisilik_Uygulamasi.Models.Entity.TBL_BILIRKISILIK

@{
    ViewBag.Title = "DosyaDetayGetir";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<h2>Rapor Teslim İşlemleri</h2>


@using (Html.BeginForm("DosyaGuncelle", "BilirkisiDosya", FormMethod.Post))
{
<div class="form-row">
    <div class="col-5" style="margin-top: 15px; margin-left: 30px;">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })

        <label>Gönderen Birim</label>
        @Html.DropDownListFor(k => k.TBL_BIRIMLER.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>Dosya No</label>
        @Html.TextBoxFor(k => k.DOSYANO, new { @class = "form-control" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>Dosya Gönderim Tarihi</label>
        @Html.TextBoxFor(k => k.GELISTARIHI, "{0: dd/MM/yyyy}", new { @class = "form-control" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>İstenen Rapor Türü</label>
        @Html.DropDownListFor(k => k.TBL_RAPORTURU.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>İşlem Yapan Bilirkişi</label>
        @Html.DropDownListFor(k => k.TBL_BILIRKISILER.ID, (List<SelectListItem>)ViewBag.dgr3, new { @class = "form-control" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>Dosya Teslim Tarihi</label>
        @Html.TextBoxFor(k => k.TESLIMTARIHI, "{0: dd/MM/yyyy}", new { @class = "form-control", @type = "date" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>Takdir Edilen Sarf Ücreti</label>
        @Html.TextBoxFor(k => k.UCRET, new { @class = "form-control" })
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <label>Dosyaya ilişkin özel not</label>
        @Html.TextAreaFor(k => k.NOTLAR, new { @class = "form-control" })
    </div>
</div>
    <br/>
    <button class="btn-warning">Kayıt Güncelle</button>
    @*//Derdest durum statüsünü false a çekecek
    <input type="hidden" name="DOSYADURUMU" value="False" />

    //Ücretlik alan durumu statüsünü true a çekecek
    <input type="hidden" name="DURUMU" value="True" />*@
    <br/>

    <div style="color: red">Dosya teslim edildiğinde ücret belli olmadığından lütfen ücret alanına 1 TL (rakamla 1) yazınız.</div>
}

Bilirkisilik_Uygulamasi/Views/BilirkisiDosya/DosyaEkle.cshtml
@model Bilirkisilik_Uygulamasi.Models.Entity.TBL_BILIRKISILIK
@{
    ViewBag.Title = "DosyaEkle";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
@using (Html.BeginForm("DosyaEkle", "BilirkisiDosya", FormMethod.Post))
{

    <div class="form-row">
        <div class="col-3" style="margin-top: 15px; margin-left: 30px;">
            <label>Gönderen Birim</label>
            @Html.DropDownListFor(k => k.TBL_BIRIMLER.ID, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
        </div>
        <div style="margin-top: 15px; margin-left: 30px;">
            <label>Dosya No</label>
            @Html.TextBoxFor(k => k.DOSYANO, new { @class = "form-control" })
        </div>
        <div style="margin-top: 15px; margin-left: 30px;">
            <label>Dosya Gönderim Tarihi</label>
            @Html.TextBoxFor(k => k.GELISTARIHI, "{0: dd/MM/yyyy}", new { @class = "form-control", @type = "date" })
            

        </div>
        <div style="margin-top: 15px; margin-left: 30px;">
            <label>İstenen Rapor Türü</label>
            @Html.DropDownListFor(k => k.TBL_RAPORTURU.ID, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
        </div>
    </div>
    <div style="margin-top: 15px; margin-left: 30px;">
        <button class="btn btn-info">Dosya Ekle</button>
    </div>
    //Durum statüsünü true ye çekecek
    <input type="hidden" name="DOSYADURUMU" value="True" />
}

Bilirkisilik_Uygulamasi/Views/BilirkisiDosya/Index.cshtml
@using Bilirkisilik_Uygulamasi.Models.Entity
@model List<TBL_BILIRKISILIK>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}
<div>
    <h2 style="margin-left: 30px; color: red">Yapılacak Dosyalar Listesi</h2>

</div>

@*Dosya numarasına göre arama*@

@using (Html.BeginForm("Index", "BilirkisiDosya", FormMethod.Get))
{
    <div style="margin-bottom: 15px; margin-top: 15px; margin-left: 30px;">
        <b>Aranacak Dosya numarasını girin : &nbsp;</b> @Html.TextBox("t")
        <input type="submit" value="Ara" />
        <a href="~/BilirkisiDosya/DosyaEkle/" class="btn btn-primary" style="margin-left: 30px;">Dosya Ekle</a>
    </div>
}


<table class="table table-bordered" style="margin-left: 30px;">
    <tr style="background: darkblue; color: white">
        <th>ID</th>
        <th>GÖNDEREN BİRİM</th>
        <th>DOSYA NO</th>
        <th>GÖNDERİM TARİHİ</th>
        <th>RAPOR TÜRÜ</th>
        <th>TESLİM ET</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.TBL_BIRIMLER.BIRIMAD</td>
            <td>@x.DOSYANO</td>
            <td>@Convert.ToDateTime(x.GELISTARIHI).ToString("dd/MM/yyyy")</td>
            <td>@x.TBL_RAPORTURU.RAPORTURU</td>
            <td><a href="~/BilirkisiDosya/DosyaDetayGetir/@x.ID" class="btn btn-success">Dosya Teslimi</a></td>

        </tr>

    }

</table>

Bilirkisilik_Uygulamasi/Views/BilirkisiDosya/SarfYazilmamisDosyalar.cshtml
@using Bilirkisilik_Uygulamasi.Models.Entity
@model List<TBL_BILIRKISILIK>

@{
    ViewBag.Title = "SarfYazilmamisDosyalar";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}


<div>
    <h2 style="margin-left: 30px; color: red">Sarf Kararı Yazılmamış Dosyalar Listesi</h2>

</div>

@*Dosya numarasına göre arama*@

@using (Html.BeginForm("Arama", "BilirkisiDosya", FormMethod.Get))
{
    <div style="margin-bottom: 15px; margin-top: 15px; margin-left: 30px;">
        <b>Aranacak Dosya numarasını girin : &nbsp;</b> @Html.TextBox("p")
        <input type="submit" value="Ara" />
    </div>
}


<table class="table table-bordered" style="margin-left: 30px;">
    <tr style="background: darkblue; color: white">
        <th>ID</th>
        <th>GÖNDEREN BİRİM</th>
        <th>DOSYA NO</th>
        <th>GÖNDERİM TARİHİ</th>
        <th>TESLİM TARİHİ</th>
        <th>RAPOR TÜRÜ</th>
        <th>ÜCRET GÜNCELLE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.TBL_BIRIMLER.BIRIMAD</td>
            <td>@x.DOSYANO</td>
            <td>@Convert.ToDateTime(x.GELISTARIHI).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(x.TESLIMTARIHI).ToString("dd/MM/yyyy")</td>
            <td>@x.TBL_RAPORTURU.RAPORTURU</td>
            @*<td>@x.TBL_BILIRKISILER.ADSOYAD</td>*@
            <td><a href="/BilirkisiDosya/UcretGuncelleDetayGetir/@x.ID" class="btn btn-success">Ücret Güncelleme</a></td>

        </tr>

    }

</table>