Bilirkisilik_Uygulamasi/Controllers/EskiDosyalarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bilirkisilik_Uygulamasi.Models.Entity;

namespace Bilirkisilik_Uygulamasi.Controllers
{
    public class EskiDosyalarController : Controller
    {
        // GET: EskiDosyalar
        DBBILIRKISIEntities1 db = new DBBILIRKISIEntities1();
        [Authorize]
        public ActionResult Index(string t)
        {
            return View(db.TBL_BILIRKISILIK.Where(x => x.DOSYANO.StartsWith(t) || t == null && x.UCRETDURUM == false).ToList());
        }
    }
}

Bilirkisilik_Uygulamasi/Views/EskiDosyalar/Index.cshtml
@using Bilirkisilik_Uygulamasi.Models.Entity
@model List<TBL_BILIRKISILIK>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<div>
    <h2 style="margin-left: 30px; color: red">Eski Yapılan Tüm Dosyalar Listesi (Arşiv)</h2>

</div>

@*Dosya numarasına göre arama*@

@using (Html.BeginForm("Index", "EskiDosyalar", FormMethod.Get))
{
    <div style="margin-bottom: 15px; margin-top: 15px; margin-left: 30px;">
        <b>Aranacak Dosya numarasını girin : &nbsp;</b> @Html.TextBox("t")
        <input type="submit" value="Ara" />
    </div>
}


<table class="table table-bordered" style="margin-left: 30px;">
    <tr style="background: darkblue; color: white">
        <th>ID</th>
        <th>GÖNDEREN BİRİM</th>
        <th>DOSYA NO</th>
        <th>GÖNDERİM TARİHİ</th>
        <th>TESLİM TARİHİ</th>
        <th>ALINACAK ÜCRET</th>
        <th>BİLİRKİŞİ</th>

    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.TBL_BIRIMLER.BIRIMAD</td>
            <td>@x.DOSYANO</td>
            <td>@Convert.ToDateTime(x.GELISTARIHI).ToString("dd/MM/yyyy")</td>
            <td>@Convert.ToDateTime(x.TESLIMTARIHI).ToString("dd/MM/yyyy")</td>
            <td>@x.UCRET</td>
            <td>@x.TBL_BILIRKISILER.ADSOYAD</td>

        </tr>

    }

</table>