Bilirkisilik_Uygulamasi/Controllers/BilirkisilerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bilirkisilik_Uygulamasi.Models.Entity;


namespace Bilirkisilik_Uygulamasi.Controllers
{
    public class BilirkisilerController : Controller
    {
        DBBILIRKISIEntities1 db = new DBBILIRKISIEntities1();

        // GET: Bilirkisiler
        [Authorize]
        public ActionResult Index()
        {
            var listeleme = db.TBL_BILIRKISILER.Where(x=>x.DURUM == true).ToList();
            return View(listeleme);
        }

        [HttpGet]
        public ActionResult BilirkisiEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BilirkisiEkle(TBL_BILIRKISILER b)
        {
            if (!ModelState.IsValid)
            {
                //Şartı sağlamadıysam
                return View("BilirkisiEkle");
            }
            db.TBL_BILIRKISILER.Add(b);
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        public ActionResult BilirkisiPasifEt(TBL_BILIRKISILER b)
        {
            var pasif = db.TBL_BILIRKISILER.Find(b.ID);
            pasif.DURUM = false;
            db.SaveChanges();
            return RedirectToAction("Index");

        }

        public ActionResult BilirkisiBilgileriGetir(int id)
        {
            var deger2 = db.TBL_BILIRKISILER.Find(id);
            return View("BilirkisiBilgileriGetir", deger2);
        }

        public ActionResult BilirkisiGuncelle(TBL_BILIRKISILER b)
        {
            var degerler = db.TBL_BILIRKISILER.Find(b.ID);
            degerler.ADSOYAD = b.ADSOYAD;
            degerler.SICIL = b.SICIL;
            degerler.EMAIL = b.EMAIL;
            degerler.KULLANICIADI = b.KULLANICIADI;
            degerler.SIFRE = b.SIFRE;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Bilirkisilik_Uygulamasi/Views/Bilirkisiler/BilirkisiBilgileriGetir.cshtml
@model Bilirkisilik_Uygulamasi.Models.Entity.TBL_BILIRKISILER

@{
    ViewBag.Title = "BilirkisiBilgileriGetir";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

<h2>Bilirkisi Bilgileri</h2>

@using (Html.BeginForm("BilirkisiGuncelle", "Bilirkisiler", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(k => k.ID)
        @Html.TextBoxFor(k => k.ID, new { @class = "form-control" })

        <label>ADI SOYADI</label>
        @Html.TextBoxFor(k => k.ADSOYAD, new { @class = "form-control" })

        <label>SİCİLİ</label>
        @Html.TextBoxFor(k => k.SICIL, new { @class = "form-control" })

        <label>Email Adresi</label>
        @Html.TextBoxFor(k => k.EMAIL, new { @class = "form-control" })
            
        <label>Kullanıcı Adı</label>
        @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control" })
            
        <label>Şifre</label>
        @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })


    </div>
    <button class="btn-warning">Güncelle</button>
}

Bilirkisilik_Uygulamasi/Views/Bilirkisiler/BilirkisiEkle.cshtml
@model Bilirkisilik_Uygulamasi.Models.Entity.TBL_BILIRKISILER

@{
    ViewBag.Title = "BilirkisiEkle";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}

@using (Html.BeginForm("BilirkisiEkle", "Bilirkisiler", FormMethod.Post))
{
    <div class="form-group">
        <div style="margin-top: 15px">
            <label>Personel Adı ve Soyadı</label>
            @Html.TextBoxFor(k => k.ADSOYAD, new { @class = "form-control" })
            
            <label>Sicili</label>
            @Html.TextBoxFor(k => k.SICIL, new { @class = "form-control" })
            
            <label>Email Adresi</label>
            @Html.TextBoxFor(k => k.EMAIL, new { @class = "form-control" })
            
            <label>Kullanıcı Adı</label>
            @Html.TextBoxFor(k => k.KULLANICIADI, new { @class = "form-control" })
            
            <label>Şifre</label>
            @Html.TextBoxFor(k => k.SIFRE, new { @class = "form-control" })


        </div>

    </div>
    <div style="margin-top: 15px">
        <button class="btn btn-info">Bilirkişi Ekle</button>
        <input type="hidden" name="DURUM" value="True" />
    </div>
}

Bilirkisilik_Uygulamasi/Views/Bilirkisiler/Index.cshtml
@using Bilirkisilik_Uygulamasi.Models.Entity
@model List<TBL_BILIRKISILER>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout_Admin.cshtml";
}


<h2 style="margin-left: 30px; color: red">Bilirkişiler</h2>

<table class="table table-bordered" style="margin-left: 30px;">
    <tr style="background: darkblue; color: white">
        <th>ID</th>
        <th>ADI SOYADI</th>
        <th>SİCİLİ</th>
        <th>EMAİL</th>
        <th>PASİF ET</th>
        <th>GÜNCELLE</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.ID</td>
            <td>@x.ADSOYAD</td>
            <td>@x.SICIL</td>
            <td>@x.EMAIL</td>
            
            <td>
                <a href="~/Bilirkisiler/BilirkisiPasifEt/@x.ID" id="btnpasif" class="btn btn-danger">Pasif Et</a>
            </td>

            <td><a href="~/Bilirkisiler/BilirkisiBilgileriGetir/@x.ID" class="btn btn-success">Güncelle</a></td>


        </tr>

    }

</table>
<a href="~/Bilirkisiler/BilirkisiEkle/" class="btn btn-primary" style="margin-left: 30px;">Bilirkişi Ekle</a>